### ISSUE TITLE
idk why lol did everything correctly

### ISSUE THREAD

**Issue by Lolpprogamer666** [o7-Fire/General#21]
node:assert:399
    throw err;
    ^

AssertionError [ERR_ASSERTION]: plugins need to be an array of functions
    at EventEmitter.loadPlugins (/home/d-shell/node_modules/mineflayer/lib/plugin_loader.js:32:12)
    at Object.<anonymous> (/home/d-shell/HIVEMIND.js:96:5)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by Itzbenz** [comment]
what is this

**Comment by Dofuscan** [comment]
what why this

**Comment by NexitySecond** [comment]
its a real issue, but mostly on your part, not sure what exactly happened but must be a js package issue
