### ISSUE TITLE
write epipe error

### ISSUE THREAD

**Issue by shadow01148** [o7-Fire/General#9]
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Framer.ondata (/home/runner/FishingBot/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Framer.emit (events.js:376:20)
    at addChunk (/home/runner/FishingBot/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/runner/FishingBot/node_modules/readable-stream/lib/_stream_readable.js:280:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

**Comment by NexitySecond** [comment]
not my problem

**Comment by Itzbenz** [comment]
provide additional infromation
